#!/system/bin/sh

#SYSTEM=/xmnt/mb/db_home/home/test/mnt
SYSTEM=/system
LINK=`readlink $SYSTEM/rilchroot`

case $LINK in 
	cm12chroot)
		ACT=1
		;;
	skkchroot)
		ACT=2
		;;
	tmchroot)
		ACT=3
		;;
	*)
		ACT=x
		echo "ERROR unknown RIL"
		;;
esac

[ "$1" = "x" ] || echo "Select RIL implementation:"

[ $ACT = 1 ] && echo -n '* ' || echo -n '  '
echo "1 - CM 12.1 based"
[ $ACT = 2 ] && echo -n '* ' || echo -n '  '
echo "2 - Stock 4.4.4 based"
[ $ACT = 3 ] && echo -n '* ' || echo -n '  '
echo "3 - TheMuppets based"

if [ -z "$1" ]
then
	echo "  x - quit"	
	echo '?'
	read n
else
        n=$1
fi

[ "$n" = "x" ] && exit 0

SELECT_RIL_CMD=<<EOF
mount -oremount,rw $SYSTEM \n
rm -f $SYSTEM/rilchroot \n
ln -s __RILCHROOT__ $SYSTEM/rilchroot \n
EOF

select_ril(){
	echo $SELECT_RIL_CMD | sed "s/__RILCHROOT__/$1/" | su -c sh
}

case $n in
        1)
                select_ril cm12chroot
                ;;
        2)
                select_ril skkchroot
                ;;
        3)
                select_ril tmchroot
                ;;
        *)
                ;;
esac


echo "\nSelected:"
$0 x
